### ISSUE TITLE
Crash after a certain period of time

### ISSUE THREAD

**Issue by MrBloodwolfie** [the-DJDJ/Monsters-And-Magic#2]
- The Game crashes after a certain period of time the game crashes and I am unable to load the world or create a new world 
- left My Pc and got distracted, saw that I died, got distracted again, got back the the game having crashed(whole app Closed) 
- 1.6
- have removed auto switch mod 
- Java platform 1.8.0_77
- Girl *stubs toe* "motherF$#%er" 
Dad *walks In* "you called?"

_On a side note I did not redowload due to the factor that if it is a time based problem it would give false results and has happened to others (crass reports added and labled I noticed initial report was much larger than the other crash reports)_
[crash-2016-04-23_18.55.51-client (first crash).txt](https://github.com/the-DJDJ/Monsters-And-Magic/files/233383/crash-2016-04-23_18.55.51-client.first.crash.txt)
[crash-2016-04-23_20.14.23-client (trying to load the world).txt](https://github.com/the-DJDJ/Monsters-And-Magic/files/233384/crash-2016-04-23_20.14.23-client.trying.to.load.the.world.txt)
[crash-2016-04-23_20.20.18-client(creating new world).txt](https://github.com/the-DJDJ/Monsters-And-Magic/files/233385/crash-2016-04-23_20.20.18-client.creating.new.world.txt)

**Comment by the-DJDJ** [comment]
Hello! Thank you for your feedback and the joke!

I have (thankfully) been able to reproduce your issue. One of the mods introduced in the latest version of the modpack is interfering with world generation, and causing the game to crash. I have, oddly enough, only found this issue on Java 8; Java 7 doesn't seem to have this problem, and the LegacyJavaFixer mod isn't helping.

At the moment I am readding the mods introduced in 1.6 one by one to a local pack to find out exactly which mod is causing the issue. I will get back to you as soon as I have more information!

**Comment by the-DJDJ** [comment]
Alright, after much tedious testing and a cup of hot chocolate, I think I have this issue sussed out.

The update to 1.6 added a few under the hood mods to improve performance, and one of those is ThreadedLighting. This was listed as a dependency for one of the mods, but as it turns out, it isn't actually needed. When I tested the modpack, I tested primarily on Java 7 as that's what I assume most users use. The issue here is that this mod only crashes on Java 8.

Rest assured however! I've tested, and it turns out the mod isn't actually needed for the game to run properly! So simply delete it from your mods folder, and let me know if that fixes the problem! Start by generating a new world, and seeing if that works, because unfortunately your existing world may have been corrupted with the issue

If this fix works properly I'll release a patch immediately! Let me know how it turns out!

**Comment by MrBloodwolfie** [comment]
you were correct as to the old world not functioning.
generating a world now works once more and getting to the amount of time for a crash shall take its time I shall Update you if it is to crash again or if I believe the problem is no longer applicable with the modification

**Comment by the-DJDJ** [comment]
Great! I have already pushed the changes to the download, anybody who downloads it from now on will have the fix. I will push the update forcing everybody to download the fix in a bit!

Thank you so much for your help!

**Comment by MrBloodwolfie** [comment]
The issue came back as I tried to continue the world that I had created a few moments ago it seems that loading the other world effected the other world?or could it have become a loading error?

**Comment by MrBloodwolfie** [comment]
I can no longer generate a world or play one the issue dissapeared for one game run new crash reports are here
[crash-2016-04-24_16.26.22-client(Loading World).txt](https://github.com/the-DJDJ/Monsters-And-Magic/files/233477/crash-2016-04-24_16.26.22-client.Loading.World.txt)
[crash-2016-04-24_16.33.20-client(World Gen).txt](https://github.com/the-DJDJ/Monsters-And-Magic/files/233476/crash-2016-04-24_16.33.20-client.World.Gen.txt)

**Comment by the-DJDJ** [comment]
I haven't been able to recreate this issue...

Can you please outline **exactly** what you've done since I sent the last recommendation? Points to include are:

- Have you loaded the (potentially corrupted) world?
- Have you tried deleting all worlds that may have been affected by the issue, and then restarting and trying again?

This one is weird because I can't reproduce it on my side. If worst comes to worst, delete the pack and download it again? I'm still researching this side!

**Comment by MrBloodwolfie** [comment]
After loading the (potentially corrupted) world the problem came back fully until I deleted all my worlds and started fresh anew 
have tested going out in and exiting the modpack completely and retrying and they have all worked so far.

**Comment by the-DJDJ** [comment]
Okay, quick update, after reading lots of other crash logs, it looks like one of the mob mods is spawning an invalid entity. And unfortunately, since I cannot reproduce the issue, I'll have to ask you to assist me...

I've done a lot of manual spawning mobs to see what crashes my game, and I managed to get a crash on spawning CowBrine... So, try deleting the Herobrine mod and seeing if the issue still persists?

**Comment by MrBloodwolfie** [comment]
after simulating the crash again and testing the situations I then removed the herobrine mod(just the file in mod didnt want to get into the gritty details of herobrine e,e) and then tried running the same world that was causing the problem and after allowing invalid blocks to be removed the game worked

**Comment by MrBloodwolfie** [comment]
Unsure Of what exactly happened both occasions I was no longer by the computer and came back to the game having crashed It does not carry through however and I can load the world should I make a new topic or could this be linked partially

[crash-2016-04-24_18.29.58-client.txt](https://github.com/the-DJDJ/Monsters-And-Magic/files/233543/crash-2016-04-24_18.29.58-client.txt)
[crash-2016-04-24_18.34.42-client.txt](https://github.com/the-DJDJ/Monsters-And-Magic/files/233542/crash-2016-04-24_18.34.42-client.txt)

**Comment by the-DJDJ** [comment]
Okay, I think that technically qualifies as a new issue, just because we're trying to keep each issue concise and to the point (:

It is, oddly enough, the same error though. Which means that another mod may have an invalid entity. For the meantime however, we know the Herobrine mod was causing this specific issue and has been resolved.

As above, I have removed the Herobrine mod from the official download, and will post an update after we've sorted out all of the kinks in the release

Thank you so much!

**Comment by the-DJDJ** [comment]
On a side note, the crash after you leave your computer alone is probably because one of the invalid entities that is crashing the game is spawning near to you and then wandering over...

**Comment by the-DJDJ** [comment]
> Unsure Of what exactly happened both occasions I was no longer by the computer and came back to the game having crashed It does not carry through however and I can load the world should I make a new topic or could this be linked partially

I know I've marked this issue as closed, but you'll be interested to know that I think I've solved the random crashes. BossCraft 2, a mod which I really hoped would work, was adding invalid mobs. This may not always have affected you, as they seem able to spawn, but Minecraft was crashing whilst trying to render them, so obviously one wandered over while you were away from your computer.

As usual, I have removed BossCraft 2 from the current mod repository, and will be posting an update shortly to resolve the issue. I'm hoping this is only a temporary retirement of BossCraft 2, but if I cannot get it to work at a later stage it may remain out of the modpack.

Thank you for your patience!
    - the_DJDJ
